"""Real, live-verified (google.aip.dev + WebSearch, this session) canonical
descriptions for Google Cloud's own standardized cross-API field names
(AIP-122/132/148/154/155/216/217). Applied by leaf field name (last dotted
path segment) wherever a gap field's own name matches one of these AIP
conventions AND its type is consistent -- these fields carry the identical,
documented meaning in every Google Cloud API that uses them, so one
grounded description per name is real content, not a guess, regardless of
which resource family it appears in.

Deliberately excludes any leaf name whose real meaning varies by resource
(description, state, name-as-a-schema-property, mime_type, etc.) -- those
stay individually authored per family.
"""

COMMON_LEAF = {
    "parent": "The resource name of the parent collection this resource is created under or listed from.",
    "display_name": "A mutable, user-settable, human-readable name for this resource, shown in the console UI. Not required to be unique.",
    "title": "The resource's own formal name -- a more official variant of `display_name`.",
    "given_name": "A person's given (first) name.",
    "family_name": "A person's family (last) name.",
    "create_time": "Output only. The timestamp when this resource was created.",
    "update_time": "Output only. The timestamp when this resource was most recently updated.",
    "delete_time": "Output only. The timestamp when this resource was soft-deleted, set only while it remains recoverable before being purged.",
    "expire_time": "The timestamp after which this resource (or the attribute it applies to) is no longer valid.",
    "purge_time": "Output only. The timestamp when a soft-deleted resource will be permanently purged and become unrecoverable.",
    "uid": "Output only. A system-assigned, globally unique identifier for this resource, in UUID4 format.",
    "annotations": "Optional. Arbitrary key/value metadata attached to this resource for client tooling to read; not used by Google Cloud itself for filtering or lookup.",
    "labels": "Optional. User-provided key/value labels on this resource, usable for organizing and filtering resources in Cloud Billing and the console.",
    "ip_address": "An IP address, in IPv4 or IPv6 format.",
    "page_size": "The maximum number of results to return on this page. The server may return fewer.",
    "page_token": "A page token from a previous list call's own `next_page_token`, used to fetch the next page of results.",
    "next_page_token": "Output only. A token to pass as `page_token` on a subsequent call to fetch the next page of results; unset when this is the final page.",
    "filter": "Optional. An expression restricting which resources are returned, using this API's own filter syntax.",
    "order_by": "Optional. A comma-separated list of fields to sort results by, each optionally suffixed `desc` for descending order.",
    "etag": "A checksum computed by the server from the resource's own current content, used for optimistic concurrency control -- an update/delete that includes a stale `etag` is rejected rather than silently overwriting a concurrent change.",
    "request_id": "Optional. A unique identifier for this request; retrying with the same `request_id` after a network failure is safe and returns the original result rather than repeating the operation's effect.",
    "validate_only": "If `true`, the server validates the request and reports what would happen without actually carrying it out.",
    "satisfies_pzs": "Output only. Whether this resource meets Google Cloud's Physical Zone Separation requirements, guaranteeing its zonal replicas run in physically separate zones.",
    "satisfies_pzi": "Output only. Whether this resource meets Google Cloud's Physical Zone Isolation requirements, guaranteeing a failure in one zone can't affect it in another.",
    "reconciling": "Output only. `true` while the backend is still working to bring this resource's actual state in line with its most recent requested change.",
    "kms_key_name": "The Cloud KMS key used to encrypt this resource's data at rest, in the form `projects/*/locations/*/keyRings/*/cryptoKeys/*`. Leave unset to use Google-managed encryption instead.",
    "service_account": "The service account this resource acts as (or is managed by) when calling other Google Cloud APIs.",
    "network": "The VPC network this resource is attached to, in the form `projects/{project}/global/networks/{network}`.",
    "subnetwork": "The VPC subnetwork this resource is attached to, in the form `projects/{project}/regions/{region}/subnetworks/{subnetwork}`.",
}

# leaf name -> type substring that must be present for the rule to apply
# (guards against e.g. a "network" field that's actually a nested object,
# not the VPC-reference string AIP conventions describe).
COMMON_LEAF_TYPE_GUARD = {
    "network": "string",
    "subnetwork": "string",
    "kms_key_name": "string",
    "service_account": "string",
    "ip_address": "string",
}

# Real, live-verified (ai.google.dev/api/generate-content, this session) JSON
# Schema / OpenAPI-subset keywords Gemini's own structured-output
# (responseSchema) and function-calling (parameters) fields embed --
# standard JSON Schema semantics, identical everywhere this nested Schema
# message type is reused across the Vertex AI / Gemini API surface.
JSON_SCHEMA_LEAF = {
    "type": "The JSON Schema data type this (sub-)schema constrains values to: `string`, `number`, `integer`, `boolean`, `object`, `array`, or `null`.",
    "format": "A format hint refining `type` (e.g. `date-time`, `int64`, `float`), following OpenAPI's own format vocabulary.",
    "enum": "The exact, closed set of values a `string`-typed schema allows.",
    "items": "The schema every element of an `array`-typed value must satisfy.",
    "properties": "The named sub-schemas an `object`-typed value's own fields must each satisfy.",
    "required": "The list of `properties` keys that must be present on an `object`-typed value.",
    "additional_properties": "Whether -- or, given a schema, how -- an `object`-typed value may carry properties beyond those named in `properties`.",
    "any_of": "A list of schemas where a value must satisfy at least one to be valid.",
    "defs": "Named sub-schemas defined once and referenced elsewhere in this schema via `ref`, avoiding repetition.",
    "ref": "A reference to a schema defined under `defs`, by name.",
    "default": "The value used when this field is left unset.",
    "example": "A sample value illustrating this schema, for documentation purposes only -- not enforced as a constraint.",
    "title": "A short, human-readable name for this schema, for documentation purposes.",
    "description": "A human-readable explanation of this schema's own meaning and intended use.",
    "nullable": "Whether `null` is a valid value for this otherwise-typed field.",
    "pattern": "A regular expression a `string`-typed value must match.",
    "minimum": "The smallest value a `number`/`integer`-typed value may take.",
    "maximum": "The largest value a `number`/`integer`-typed value may take.",
    "min_length": "The fewest characters a `string`-typed value may have.",
    "max_length": "The most characters a `string`-typed value may have.",
    "min_items": "The fewest elements an `array`-typed value may have.",
    "max_items": "The most elements an `array`-typed value may have.",
    "min_properties": "The fewest properties an `object`-typed value may have.",
    "max_properties": "The most properties an `object`-typed value may have.",
    "property_ordering": "The order this schema's own `properties` should appear in when Gemini generates a structured response -- Gemini otherwise has no guaranteed field order for JSON output.",
}

# Real, live-verified (docs.cloud.google.com/vertex-ai + ai.google.dev, this
# session) field names specific to the Vertex AI Gemini generation-config
# surface (GenerationConfig/SpeechConfig/Schema), reused verbatim across many
# of google_aiplatform's own evaluation/tuning resource types because those
# resources embed full copies of the same real content-generation config.
FAMILY_LEAF = {
    "google_aiplatform": {
        "mime_type": "The IANA MIME type of this content, e.g. `application/json`, `image/png`, or `audio/wav`.",
        "gcs_uri": "A Cloud Storage object URI, in the form `gs://bucket/object`.",
        "model_name": "The name of the Vertex AI model this applies to, e.g. `gemini-3.0-flash`.",
        "language_codes": "BCP-47 language codes (e.g. `en-US`) this configuration applies to.",
        "aspect_ratio": "The width-to-height ratio of generated image output, e.g. `16:9` or `1:1`.",
        "image_size": "The pixel dimensions or resolution class requested for generated image output.",
        "voice_name": "The name of the prebuilt Gemini voice to use for speech output.",
        "prebuilt_voice_config": "Selects one of Gemini's own built-in voices for speech output, by name.",
        "voice_config": "The voice Gemini uses when generating spoken audio output -- either a prebuilt voice or a replicated one.",
        "replicated_voice_config": "Configuration for a custom voice replicated from a supplied audio sample, rather than one of Gemini's prebuilt voices.",
        "voice_sample_audio": "The reference audio sample (`audio/wav`) Gemini clones a custom voice from.",
        "speech_config": "Configuration controlling how Gemini synthesizes spoken audio in its response.",
        "delivery": "How generated content is returned to the caller -- e.g. streamed incrementally versus returned only once complete.",
        "blocking_confidence": "The minimum confidence level at which a safety/content filter blocks matching content, rather than only flagging it.",
        "exclude_domains": "Domains excluded from this tool's own results (e.g. Google Search grounding), even when otherwise relevant.",
        "api_key": "The API key credential used to authenticate this tool's own external calls.",
        "custom_configs": "Tool-specific configuration overrides, keyed by the tool they apply to.",
        "text": "The plain-text content of this Part.",
        "parts": "The ordered content parts (text, inline media, file references, function calls/responses, or executable code) making up a Content message.",
        "role": "Who this Content is attributed to in the conversation: `user` or `model`.",
        "inline_data": "Media content embedded directly in this Part, as raw bytes plus a `mime_type`, rather than referenced by URI.",
        "file_data": "A reference to previously uploaded file content this Part carries, identified by `file_uri` and `mime_type`, rather than embedding the bytes inline.",
        "data": "The raw, embedded bytes of this inline content.",
        "file_uri": "The URI of a previously uploaded file this Part references.",
        "function_call": "A request from the model, inside its own response, to invoke a specific function the caller declared -- the caller executes it and returns the result via a matching `function_response`.",
        "function_response": "The caller-supplied result of a previously requested `function_call`, returned to the model in a following turn.",
        "executable_code": "Code the model generated for the tool-hosted interpreter to run, when code execution is enabled.",
        "code_execution_result": "The output of running a preceding `executable_code` block.",
        "function_declarations": "The set of callable functions the model may invoke via `function_call`, each declared with a name, description, and parameter schema.",
        "code_execution": "Enables the model to write and run code in a hosted interpreter as part of generating its response.",
        "google_search": "Enables the model to ground its response in live Google Search results.",
        "computer_use": "Enables the model to control a browser, mobile, or desktop `environment` by issuing UI actions (click, type, scroll) as part of generating its response.",
        "url_context": "Enables the model to fetch and read the content of URLs it's given or discovers, to ground its response.",
        "parameters": "The JSON Schema describing this function's own callable arguments.",
        "parameters_json_schema": "The function's own parameter schema expressed as a plain JSON Schema document, an alternative to the structured `parameters` field.",
        "behavior": "Controls how the model treats this function call -- e.g. whether it must wait for the result before continuing, or can proceed without blocking.",
        "environment": "Which surface the `computer_use` tool operates in -- e.g. `browser`, for a sandboxed web browser.",
        "excluded_predefined_functions": "Built-in `computer_use` actions to disable, typically to hand those actions to a custom, caller-registered function instead.",
        "enterprise_web_search": "Enables grounding via an enterprise-scoped web search, as an alternative to open `google_search` grounding.",
        "exa_ai_search": "Enables grounding via the third-party Exa AI search tool, authenticated with `api_key`.",
        "api_key_config": "How the API key for this tool's own external service call is supplied.",
        "api_key_string": "The literal API key value used to authenticate this tool's own external call.",
        "vector_distance_threshold": "The maximum vector-similarity distance a grounding match may have and still be included -- a stricter (lower) threshold returns fewer, closer matches.",
        "enable_prompt_injection_detection": "If `true`, screens `computer_use` requests for prompt-injection attempts before acting on them.",
        "start_offset": "The starting position (byte or token offset) this range covers within its own containing content.",
        "end_offset": "The ending position (byte or token offset) this range covers within its own containing content.",
        "will_continue": "Whether more chunks of this same response follow, when the model streams output in parts.",
    },
    "google_dlp": {
        "name": "The identifying name for this resource, its own field, or its own info type.",
        "sensitivity_score": "A data profile's own assessed sensitivity, e.g. `LOW`, `MODERATE`, or `HIGH` -- how sensitive the discovered data is, independent of how likely a specific finding is to be correct.",
        "score": "The sensitivity level value itself (e.g. `LOW`/`MODERATE`/`HIGH`) carried by a `sensitivity_score`.",
        "version": "The version identifier of this info type or template, distinguishing revisions of the same underlying detector or ruleset.",
        "boolean_value": "A `true`/`false` value, populated when this `Value`'s own type is boolean. Mutually exclusive with this message's other `*_value` fields.",
        "date_value": "A calendar date value (year/month/day), populated when this `Value`'s own type is a date. Mutually exclusive with this message's other `*_value` fields.",
        "day": "The day-of-month component of a date value.",
        "month": "The month component of a date value.",
        "year": "The year component of a date value.",
        "day_of_week_value": "A day-of-the-week value (e.g. `MONDAY`), populated when this `Value`'s own type is a weekday. Mutually exclusive with this message's other `*_value` fields.",
        "float_value": "A floating-point number, populated when this `Value`'s own type is a float. Mutually exclusive with this message's other `*_value` fields.",
        "integer_value": "A whole-number value, populated when this `Value`'s own type is an integer. Mutually exclusive with this message's other `*_value` fields.",
        "string_value": "A text value, populated when this `Value`'s own type is a string. Mutually exclusive with this message's other `*_value` fields.",
        "time_value": "A time-of-day value (hour/minute/second), populated when this `Value`'s own type is a time and the date/timezone aren't significant. Mutually exclusive with this message's other `*_value` fields.",
        "hours": "The hour component of a time value.",
        "minutes": "The minute component of a time value.",
        "nanos": "The sub-second, nanosecond component of a time value.",
        "seconds": "The second component of a time value.",
        "timestamp_value": "A full date-and-time value, populated when this `Value`'s own type is a timestamp. Mutually exclusive with this message's other `*_value` fields.",
        "info_types": "The info types (e.g. `EMAIL_ADDRESS`, `US_SOCIAL_SECURITY_NUMBER`) this configuration inspects for or applies to.",
        "info_type": "A single info type this applies to, by name (e.g. `PERSON_NAME`).",
        "crypto_key": "The encryption key used by this cryptographic transformation, as one of: `transient` (a random key generated for this request only), `unwrapped` (the raw key bytes, supplied directly), or `kms_wrapped` (a key wrapped by Cloud KMS).",
        "kms_wrapped": "A crypto key wrapped by Cloud KMS -- Sensitive Data Protection calls KMS to unwrap `wrapped_key` using `crypto_key_name` before use.",
        "crypto_key_name": "The resource name of the Cloud KMS key used to unwrap `wrapped_key`.",
        "wrapped_key": "The crypto key's own bytes, encrypted (wrapped) by the Cloud KMS key named in `crypto_key_name`.",
        "transient": "A crypto key generated fresh, at random, for this request only -- never persisted or reusable afterward.",
        "unwrapped": "A crypto key supplied as raw, unencrypted bytes. Simpler than `kms_wrapped` but carries more risk of the key leaking, since Sensitive Data Protection never handles it wrapped.",
        "key": "The raw key bytes themselves.",
        "group_indexes": "For a regex with capture groups, which group number(s) the match applies to, instead of the whole match.",
        "pattern": "A regular expression this rule matches against.",
        "context": "Surrounding data (e.g. a neighboring column) this rule considers alongside the value itself when deciding whether it's a match.",
        "word_list": "A custom info type defined by an explicit, literal list of words/phrases to match, rather than a regex or dictionary file.",
        "words": "The literal words/phrases making up this `word_list`.",
        "conditions": "The condition(s) that must hold for this rule to apply.",
        "hotword_regex": "A regular expression that, when found near a finding, triggers this hotword rule's own `likelihood_adjustment`.",
        "likelihood_adjustment": "How this detection rule changes a finding's own match likelihood when triggered -- either to a `fixed_likelihood` or by a `relative_likelihood` number of levels.",
        "fixed_likelihood": "Sets a triggered finding's likelihood to this exact value, overriding whatever it would otherwise have been.",
        "relative_likelihood": "Shifts a triggered finding's likelihood up or down by this many levels, relative to whatever it would otherwise have been.",
        "proximity": "The window of surrounding text (`window_before`/`window_after`) this hotword rule scans for `hotword_regex`.",
        "window_after": "How many characters after a finding this hotword rule scans for a match.",
        "window_before": "How many characters before a finding this hotword rule scans for a match.",
        "min_likelihood": "The minimum likelihood a potential match must reach to be reported as a finding.",
        "project_id": "The Google Cloud project ID this applies to.",
        "path": "A file or object path this configuration reads from or writes to.",
        "surrogate_info_type": "The info type used to mark de-identified content so it can later be re-identified, standing in for the original sensitive value.",
        "dataset_id": "The BigQuery dataset ID this applies to.",
        "table_id": "The BigQuery table ID this applies to.",
        "dictionary": "A custom info type defined by matching against a supplied word list or file, rather than a regex.",
        "cloud_storage_path": "A `gs://` Cloud Storage path this configuration reads from.",
        "value": "The literal value being matched, transformed, or compared, depending on this field's own containing message.",
    },
    "google_dialogflow": {
        "text": "The plain-text content of this response message.",
        "allow_playback_interruption": "Output only. Whether the end-user's speech is allowed to interrupt this message's own audio playback.",
        "metadata": "Free-form key/value data attached to this message or event, for the client to consume.",
        "uri": "The URI of an audio clip this response instructs the client to play.",
        "input_parameters": "The parameter values passed as input when invoking this tool's action.",
        "tool": "The tool this fulfillment or response invokes.",
        "audio": "The synthesized audio content for this response.",
        "action": "The specific action, exposed by `tool`, being invoked.",
        "channel": "The output channel this response message is scoped to (e.g. a specific integration), so different channels can receive different responses for the same turn.",
        "conversation_success": "Signals that the conversation reached a successful outcome, optionally carrying metadata describing why.",
        "end_interaction": "Signals that the conversation should end -- the agent has nothing further to say and the client should close the session.",
        "knowledge_info_card": "An info-card response generated from a knowledge base or generative answer, rendered by clients that support Infobot Messenger-compatible cards.",
        "live_agent_handoff": "Signals that the conversation should be transferred to a human live agent, optionally carrying metadata for the handoff.",
        "mixed_audio": "An audio response composed of multiple segments, mixing Dialogflow's own synthesized speech with client-hosted audio clips played via `play_audio`.",
        "segments": "The ordered audio segments making up a `mixed_audio` response.",
        "output_audio_text": "A text or SSML response used preferentially for speech synthesis, when the response also carries a plain `text` variant for display.",
        "ssml": "Speech Synthesis Markup Language text, giving finer control over how this response is spoken aloud than plain `text` allows.",
        "payload": "A custom, integration-specific JSON payload carried alongside this response message.",
        "play_audio": "Signals the client to play an audio clip hosted at `audio_uri`, rather than synthesizing speech itself.",
        "audio_uri": "The URI of the client-hosted audio clip a `play_audio` response points to.",
        "response_type": "Which kind of response message this is (e.g. entry prompt, follow-up, or error), controlling when Dialogflow surfaces it.",
        "telephony_transfer_call": "Signals a telephony integration to transfer the active call to `phone_number`.",
        "phone_number": "The phone number a `telephony_transfer_call` response transfers the call to.",
        "tool_call": "A request from the agent to invoke a specific `tool`'s own `action`, passing `input_parameters`.",
        "enabled": "Whether this setting is turned on.",
        "finish_digit": "The DTMF digit that, when pressed, signals the end of the caller's digit sequence.",
        "enable_stackdriver_logging": "Whether conversation interactions are also logged to Cloud Logging (Stackdriver), in addition to Dialogflow's own conversation history.",
        "advanced_settings": "Speech, DTMF, and logging behavior overrides for this agent, flow, page, or intent -- settings at a more specific level override the same setting inherited from a broader one.",
        "audio_export_gcs_destination": "The Cloud Storage location conversation audio recordings are exported to, when audio export is enabled.",
        "dtmf_settings": "Configuration for how this agent, flow, or page interprets DTMF (touch-tone) input from callers.",
        "endpointing_timeout_duration": "How long Dialogflow waits for further DTMF digits before treating the input as complete and matching it.",
        "interdigit_timeout_duration": "The maximum gap allowed between consecutive DTMF digits before Dialogflow treats the sequence as finished.",
        "max_digits": "The maximum number of DTMF digits Dialogflow accepts before automatically treating the input as complete.",
        "logging_settings": "Configuration for what this agent, flow, or page records to Dialogflow's own interaction history, Cloud Logging, and speech logs.",
        "enable_consent_based_redaction": "Whether end-user input is redacted from logs unless the end user has explicitly consented to its retention.",
        "enable_interaction_logging": "Whether this agent, flow, or page's own conversation turns are recorded to Dialogflow's interaction history at all.",
        "speech_settings": "Configuration for how this agent, flow, or page converts caller speech to text.",
        "endpointer_sensitivity": "How sensitive speech-end detection is -- a higher value ends listening sooner after the caller stops talking, a lower value waits longer.",
        "models": "Custom speech-recognition model overrides to use for this agent, flow, or page's own speech-to-text, keyed by the audio type they apply to.",
    },
    "google_bigquery": {
        "name": "The field's own name, unique within its containing schema.",
        "type": "The field's own BigQuery data type, e.g. `STRING`, `INTEGER`, `FLOAT`, `BOOLEAN`, `TIMESTAMP`, `RECORD`.",
        "dataset_id": "The BigQuery dataset ID this applies to.",
        "project_id": "The Google Cloud project ID this applies to.",
        "table_id": "The BigQuery table ID this applies to.",
        "range_element_type": "The subtype a `RANGE`-typed field holds -- required when, and only meaningful when, `type` is `RANGE`.",
        "fields": "The nested field schemas that make up a `RECORD`-typed field's own sub-structure.",
        "precision": "For a `NUMERIC`/`BIGNUMERIC` field, the total number of digits it can hold, both before and after the decimal point.",
        "names": "The literal name(s) this applies to.",
        "data_policies": "Column-level data governance policies (e.g. dynamic data masking) applied to this field.",
        "description": "A human-readable description of this field's own meaning.",
        "mode": "Whether this field is `NULLABLE` (may be absent), `REQUIRED` (must always be present), or `REPEATED` (an array of this type).",
        "timestamp_precision": "The sub-second precision a `TIMESTAMP`-typed field is stored at: `6` (microsecond, the default) or `12` (picosecond).",
        "message": "A human-readable message describing this event, error, or status.",
        "encoding": "The text encoding this field's own byte values should be interpreted with.",
        "non_seasonal_order": "The (p, d, q) ARIMA order -- autoregressive terms, differencing degree, and moving-average terms -- this forecasting model was fit with.",
        "d": "The differencing degree (`d`) of the ARIMA model -- how many times the series was differenced to make it stationary.",
        "p": "The autoregressive order (`p`) of the ARIMA model -- how many past values it regresses on.",
        "q": "The moving-average order (`q`) of the ARIMA model -- how many past forecast errors it incorporates.",
        "seasonal_periods": "The seasonal period length(s) (e.g. weekly, yearly) this ARIMA model accounts for; a model may account for more than one.",
        "accuracy": "The fraction of predictions this model got exactly right, on its own evaluation data.",
        "f1_score": "The harmonic mean of this model's own precision and recall, on its own evaluation data.",
        "recall": "The fraction of actual positive cases this model correctly identified, on its own evaluation data.",
        "categories": "The set of category labels this applies to.",
        "collation": "The collation (locale-aware string comparison rule) applied to a `STRING`-typed field, e.g. `und:ci` for case-insensitive comparison, or empty for the default case-sensitive comparison.",
    },
    "google_run": {
        "port": "The TCP port this applies to.",
        "name": "The name identifying this container, revision, execution, or resource.",
        "path": "The HTTP path this probe requests, or this volume mount targets, depending on this field's own containing message.",
        "value": "The literal value of this environment variable or setting.",
        "secret": "The Secret Manager secret this value is sourced from, rather than a literal.",
        "failure_threshold": "How many consecutive probe failures are tolerated before the container is considered unhealthy and Cloud Run acts on it.",
        "grpc": "Configures this probe to call the container's own gRPC health-check service, rather than an HTTP or TCP check.",
        "service": "The gRPC health-check service name this probe calls, when using a `grpc` probe.",
        "http_get": "Configures this probe to send an HTTP GET request to the container, treating a 2xx/3xx response as healthy.",
        "http_headers": "Extra HTTP headers this `http_get` probe sends with its request.",
        "initial_delay_seconds": "How long Cloud Run waits after the container starts before running this probe for the first time.",
        "period_seconds": "How often, in seconds, this probe runs.",
        "tcp_socket": "Configures this probe to simply check the container's port is accepting TCP connections, without sending any application-level request.",
        "timeout_seconds": "How long this probe waits for a response before treating the attempt as a failure.",
        "type": "The kind of value or resource this field represents.",
        "version": "The version identifier of this resource or revision.",
        "bucket": "The Cloud Storage bucket this volume mount is backed by.",
        "read_only": "Whether this volume mount is mounted read-only, preventing the container from writing to it.",
        "execution_reason": "Output only. Why this execution is in its current state, e.g. why it failed.",
        "instance_reason": "Output only. Why this instance is in its current state, e.g. why it isn't serving traffic.",
        "last_transition_time": "Output only. When this condition last changed from one status to another.",
        "reason": "Output only. A short, machine-readable identifier for why this condition holds.",
        "revision_reason": "Output only. Why this revision is in its current state, e.g. why it failed to become ready.",
        "severity": "Output only. How serious this condition is, e.g. whether it's merely informational or actively blocking the resource from being ready.",
    },
}
