"""Real, live-verified (learn.microsoft.com, this session) canonical
descriptions for Azure Resource Manager's own standardized field names --
the ARM resource envelope, present nearly verbatim on every ARM resource
and every nested sub-resource reference. Applied by leaf field name (last
dotted path segment), same discipline as common_gcp_fields.py's AIP dict.
"""

ARM_COMMON = {
    "id": "The fully qualified Azure Resource Manager resource ID, in the form `/subscriptions/{id}/resourceGroups/{group}/providers/{provider}/.../{name}`.",
    "name": "The resource's own name, unique within its parent scope.",
    "type": "The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`.",
    "location": "The Azure region this resource is deployed to, e.g. `eastus`.",
    "tags": "User-defined key/value tags on this resource, usable for organizing and filtering resources across the subscription.",
    "etag": "A read-only, server-generated value used for optimistic concurrency control -- an update whose own `etag` doesn't match the resource's current value is rejected rather than silently overwriting a concurrent change.",
    "properties": "The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags).",
    "provisioning_state": "The last, current provisioning status ARM reported for this resource, e.g. `Succeeded`, `Failed`, or `Updating`.",
    "resource_guid": "A stable, ARM-assigned unique identifier for this resource that survives a rename or a move across resource groups/subscriptions -- unlike `id`, which changes when either of those happens.",
    "system_data": "Output only. Metadata about this resource's own creation and last modification -- who made the change and when.",
    "sku": "The pricing tier and capacity this resource is provisioned at.",
    "tier": "The service tier this resource (or its `sku`) is provisioned at, e.g. `Standard` or `Premium`.",
    "kind": "A finer-grained classification of this resource within its own resource type, when the type supports more than one variant.",
    "zones": "The Availability Zone(s) this resource is pinned to, within its own region.",
    "extended_location": "The edge or custom location (e.g. an Azure Extended Zone or Arc-connected site) this resource is deployed to, when it isn't a standard Azure region.",
    "principal_id": "Output only. The Microsoft Entra ID object ID of this resource's own managed identity or service principal.",
    "tenant_id": "Output only. The Microsoft Entra ID tenant this resource's own managed identity belongs to.",
    "identity": "The managed identity (or identities) this resource uses to authenticate to other Azure services.",
}

# Real, live-verified (Microsoft.Network's own well-documented, stable REST
# API surface -- LoadBalancer/ApplicationGateway/VirtualNetworkGateway/
# ExpressRoute/VirtualWan) field names, reused verbatim across every
# azure_network_* family because ARM's Network resource provider models
# nearly everything (subnets, IP configs, security rules, gateways) as
# cross-references into the SAME shared object graph -- this is the same
# real pathology already identified and describe_exclude'd for
# azure_network_virtualnetwork itself; these dictionaries cover the
# genuinely-included remainder of that same graph in the other network
# families.
ARM_NETWORK = {
    "subnet": "A reference to the subnet this resource is associated with.",
    "subnets": "The subnets belonging to this virtual network or gateway.",
    "private_ipaddress": "The private (internal) IP address assigned to this IP configuration.",
    "private_ipallocation_method": "Whether `private_ipaddress` is `Static` (fixed, caller-assigned) or `Dynamic` (assigned automatically from the subnet's own range).",
    "public_ipaddress": "A reference to the Public IP Address resource associated with this IP configuration.",
    "ip_configurations": "The IP configuration(s) (private/public address, subnet) attached to this resource.",
    "nat_gateway": "A reference to the NAT Gateway this subnet or IP configuration routes outbound traffic through.",
    "service_gateway": "A reference to the service (VPN/ExpressRoute) gateway associated with this resource.",
    "priority": "The relative priority of this rule -- lower numbers are evaluated first, and the first matching rule wins.",
    "access": "Whether this security rule's own match is `Allow`ed or `Deny`ed.",
    "direction": "Whether this security rule applies to `Inbound` or `Outbound` traffic.",
    "destination_address_prefix": "The destination IP address range (CIDR) or tag this rule matches, e.g. `10.0.0.0/24` or `Internet`.",
    "destination_address_prefixes": "The destination IP address ranges (CIDR) this rule matches, when more than one applies.",
    "destination_application_security_groups": "The Application Security Groups this rule matches traffic destined for, instead of a raw address prefix.",
    "destination_port_range": "The destination port range this rule matches, e.g. `80` or `1000-2000`.",
    "destination_port_ranges": "The destination port ranges this rule matches, when more than one applies.",
    "source_address_prefix": "The source IP address range (CIDR) or tag this rule matches, e.g. `10.0.0.0/24` or `Internet`.",
    "source_address_prefixes": "The source IP address ranges (CIDR) this rule matches, when more than one applies.",
    "source_application_security_groups": "The Application Security Groups this rule matches traffic originating from, instead of a raw address prefix.",
    "source_port_range": "The source port range this rule matches, e.g. `*` for any port.",
    "source_port_ranges": "The source port ranges this rule matches, when more than one applies.",
    "protocol": "The network protocol this rule or listener applies to, e.g. `Tcp`, `Udp`, or `*` for any.",
    "idle_timeout_in_minutes": "How many minutes an idle connection is kept open before this resource closes it.",
    "ddos_settings": "DDoS protection configuration for this public IP or virtual network.",
    "ddos_custom_policy": "A reference to a custom DDoS protection policy to apply, overriding the subscription's own default DDoS policy.",
    "fqdn": "The fully qualified domain name assigned to this resource.",
    "enabled": "Whether this feature or setting is turned on.",
    "description": "A user-supplied, human-readable note explaining this resource's own purpose.",
    "public_ipprefix": "A reference to the Public IP Prefix resource this address is allocated from.",
    "network_interfaces": "The network interface(s) attached to this resource.",
    "ip_address": "An IP address value.",
    "link": "A reference to a related resource.",
    "linked_resource_type": "The Azure resource type of the resource `link` points to.",
    "locations": "The Azure region(s) this configuration or availability applies to.",
    "service": "The Azure service (e.g. a specific Private Link-enabled PaaS service) this configuration applies to.",
    "address_prefix": "An IP address range in CIDR notation, e.g. `10.0.0.0/24`.",
    "dns_settings": "DNS configuration for this public IP address, controlling its own domain name label and reverse DNS record.",
    "migration_phase": "Which phase of a live migration (e.g. between IP address versions or gateway SKUs) this resource is currently in.",
    "private_link_service_connection_state": "The current approval state of this private endpoint's own connection to the target Private Link service -- whether it's been approved, rejected, or still pending, and any action the service owner still needs to take.",
    "actions_required": "Output only. Any action the Private Link service owner still needs to take on this connection beyond the basic approve/reject/disconnect workflow, or `None` if nothing further is needed.",
    "status": "The current status of this connection, resource, or operation, e.g. `Approved`, `Pending`, `Rejected`, or `Disconnected`.",
    "private_ipaddress_version": "Whether the private IP address for this configuration is `IPv4` or `IPv6`.",
    "ddos_protection_plan": "A reference to the DDoS Protection Plan covering this virtual network.",
    "protection_mode": "Whether DDoS protection for this resource is `Enabled`, `Disabled`, or inherits from the containing virtual network.",
    "delete_option": "What happens to this resource when its own parent (e.g. the VM or NIC it's attached to) is deleted -- `Delete` it too, or `Detach` and leave it standing.",
    "domain_name_label": "The DNS label whose concatenation with the region's own DNS zone forms this public IP address's fully qualified domain name.",
    "domain_name_label_scope": "How uniquely `domain_name_label` must be scoped -- e.g. tenant-wide or subscription-wide -- when generating this address's own FQDN.",
    "reverse_fqdn": "A fully qualified domain name that resolves to this public IP address, creating a matching reverse-DNS (PTR) record.",
    "ip_configuration": "A reference to the IP configuration this resource is associated with.",
    "ip_tags": "IP address tags -- provider-assigned category labels (e.g. for a specific Azure service edge) attached to this public IP address.",
    "first_party_service_tag_id": "The identifier of the Microsoft first-party service tag this IP tag is associated with.",
    "ip_tag_type": "The category this IP tag belongs to, e.g. `FirstPartyUsage`.",
    "tag": "The literal tag value.",
    "linked_public_ipaddress": "A reference to a second Public IP Address resource this one is linked to, e.g. its own IPv4/IPv6 counterpart.",
    "nat64": "Whether NAT64 (IPv6-to-IPv4 translation) is enabled for this configuration.",
    "public_ip_addresses": "The IPv4 Public IP Address resources associated with this configuration.",
    "public_ip_addresses_v6": "The IPv6 Public IP Address resources associated with this configuration.",
    "public_ip_prefixes": "The IPv4 Public IP Prefix resources associated with this configuration.",
    "public_ip_prefixes_v6": "The IPv6 Public IP Prefix resources associated with this configuration.",
    "source_virtual_network": "A reference to the virtual network this resource is sourced from.",
    "public_ipaddress_version": "Whether this public IP address is `IPv4` or `IPv6`.",
    "public_ipallocation_method": "Whether this public IP address is `Static` (fixed for the resource's lifetime) or `Dynamic` (may change if the resource is deleted and recreated).",
    "service_public_ipaddress": "The Public IP Address resource this managed service uses for outbound/inbound connectivity.",
    "upgraded_to_v2": "Whether this resource has been upgraded to its own newer, v2 SKU/architecture.",
    "network_security_group": "A reference to the Network Security Group applied to this subnet or network interface.",
    "primary": "Whether this is the primary configuration among several attached to the same resource.",
    "client_id": "The client (application) ID of the user-assigned managed identity to use.",
    "user_assigned_identities": "The user-assigned managed identities associated with this resource, keyed by their own resource ID.",
    "enabled_filtering_criteria": "Which traffic characteristics this flow log filters on before recording.",
    "flow_analytics_configuration": "Configuration for deriving Traffic Analytics insights from this flow log's own recorded data.",
    "network_watcher_flow_analytics_configuration": "Traffic Analytics settings (workspace, interval) applied to this Network Watcher flow log.",
    "traffic_analytics_interval": "How often, in minutes, Traffic Analytics processes this flow log's own data into insights.",
    "workspace_id": "The Log Analytics workspace ID Traffic Analytics results are sent to.",
    "workspace_region": "The Azure region the target Log Analytics workspace is deployed in.",
    "workspace_resource_id": "The full Azure Resource Manager resource ID of the target Log Analytics workspace.",
    "format": "The output format this data is written in.",
    "version": "The format or schema version this data conforms to.",
    "record_types": "Which categories of record this configuration includes.",
    "retention_policy": "How long this flow log's own recorded data is kept before automatic deletion.",
    "days": "The number of days data is retained before automatic deletion.",
    "storage_id": "The resource ID of the storage account this flow log's own data is written to.",
    "target_resource_guid": "Output only. The stable `resource_guid` of the resource this flow log is enabled on.",
    "target_resource_id": "The resource ID this configuration applies to, e.g. the NSG or virtual network a flow log is enabled on.",
    "default_security_rules": "Output only. The built-in security rules Azure automatically adds to every Network Security Group, which can't be removed (only overridden by a higher-priority custom rule).",
    "flow_logs": "The flow log(s) configured on this Network Security Group.",
    "flush_connection": "Whether existing, already-established connections are re-evaluated (and dropped if no longer allowed) immediately when this security rule changes, rather than only affecting new connections.",
    "group_ids": "The sub-resource(s) of the target service this private endpoint connects to, e.g. `blob` for a Storage account's blob endpoint.",
    "private_link_service_id": "The resource ID of the Private Link service (or Private Link-enabled PaaS resource) this private endpoint connects to.",
    "security_rules": "The custom (non-default) security rules on this Network Security Group.",
    "gateway_load_balancer": "A reference to a Gateway Load Balancer this resource chains its traffic through, for third-party network virtual appliance inspection.",
    "inbound_nat_rules": "The inbound NAT rules on this load balancer, each forwarding one external port to one specific backend instance.",
    "load_balancing_rules": "The load-balancing rules on this load balancer, each mapping a frontend IP/port to a backend pool.",
    "outbound_rules": "The outbound NAT rules on this load balancer, controlling how backend instances reach the internet through it.",
    "actions": "The action(s) this rule or policy applies.",
    "service_name": "The name of the Azure service this configuration applies to or connects with.",
    "allocated_address_prefixes": "Output only. The specific address ranges actually allocated from this pool.",
    "number_of_ip_addresses": "How many IP addresses to allocate from this pool.",
    "pool": "A reference to the address or backend pool this resource draws from or belongs to.",
    "has_bgp_override": "Whether a static route on this route table overrides the equivalent route learned via BGP.",
    "next_hop": "Where traffic matching this route is sent next.",
    "next_hop_ip_address": "The IP address traffic matching this route is forwarded to, when `next_hop_type` is `VirtualAppliance`.",
    "next_hop_ip_addresses": "Output only. The effective next-hop IP address(es) actually in use for this route.",
    "next_hop_type": "The kind of next hop this route uses, e.g. `VirtualAppliance`, `VnetLocal`, `Internet`, or `None`.",
    "allow_delete": "Whether this resource can be deleted directly, or is protected because something else still depends on it.",
    "contextual_service_endpoint_policies": "Service endpoint policies that apply to this subnet only in specific contexts (e.g. a specific service alias), layered on top of its own regular `service_endpoint_policies`.",
    "service_alias": "The alias identifying the specific PaaS service resource a service endpoint policy definition grants access to.",
    "service_endpoint_policy_definitions": "The individual rules making up a service endpoint policy, each granting subnet traffic access to a specific Azure service resource.",
    "service_resources": "The specific service resource(s) a service endpoint policy definition grants access to.",
    "network_identifier": "An identifier for the network this configuration is scoped to.",
    "address_prefixes": "The IP address ranges (CIDR), in the plural form, this resource covers.",
    "application_gateway_ipconfigurations": "The IP configuration(s) an Application Gateway uses within this subnet.",
    "default_outbound_access": "Whether this subnet gets default outbound internet access without an explicit NAT Gateway, load balancer, or public IP.",
    "delegations": "Delegates this subnet's own control to a specific Azure PaaS service, letting that service manage resources directly inside it.",
    "ip_allocations": "References to IP address pool allocations reserved for this subnet.",
    "ip_configuration_profiles": "Reusable IP configuration templates associated with this resource.",
    "ipam_pool_prefix_allocations": "Address prefixes allocated to this virtual network from an IP Address Management (IPAM) pool.",
    "private_endpoint": "A reference to the Private Endpoint resource this connection belongs to.",
    "private_endpoint_network_policies": "Whether network security group and route table policies are enforced (`Enabled`) or bypassed (`Disabled`) for private endpoints in this subnet.",
    "private_endpoints": "The Private Endpoint resources deployed in this subnet.",
    "private_link_service_network_policies": "Whether network security group and route table policies are enforced (`Enabled`) or bypassed (`Disabled`) for Private Link services in this subnet.",
    "purpose": "Output only. What this resource is being used for, when it was created automatically on behalf of another resource.",
    "resource_navigation_links": "Output only. Links to the specific external resource(s) that own or manage this subnet, when it was delegated to or created by another Azure service.",
    "route_table": "A reference to the route table associated with this subnet.",
    "disable_bgp_route_propagation": "Whether routes learned via BGP are prevented from propagating into this route table.",
    "disable_peering_route": "Whether this route is withheld from propagating to a peered virtual network.",
    "routes": "The custom routes making up this route table.",
    "service_association_links": "Output only. Links identifying the Azure service(s) this subnet has been associated with, e.g. by delegation.",
}
