"""Real, live-verified (learn.microsoft.com, this session) canonical
descriptions for Azure Resource Manager's own standardized field names --
the ARM resource envelope, present nearly verbatim on every ARM resource
and every nested sub-resource reference. Applied by leaf field name (last
dotted path segment), same discipline as common_gcp_fields.py's AIP dict.
"""

ARM_COMMON = {
    "id": "The fully qualified Azure Resource Manager resource ID, in the form `/subscriptions/{id}/resourceGroups/{group}/providers/{provider}/.../{name}`.",
    "name": "The resource's own name, unique within its parent scope.",
    "type": "The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`.",
    "location": "The Azure region this resource is deployed to, e.g. `eastus`.",
    "tags": "User-defined key/value tags on this resource, usable for organizing and filtering resources across the subscription.",
    "etag": "A read-only, server-generated value used for optimistic concurrency control -- an update whose own `etag` doesn't match the resource's current value is rejected rather than silently overwriting a concurrent change.",
    "properties": "The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags).",
    "provisioning_state": "The last, current provisioning status ARM reported for this resource, e.g. `Succeeded`, `Failed`, or `Updating`.",
    "resource_guid": "A stable, ARM-assigned unique identifier for this resource that survives a rename or a move across resource groups/subscriptions -- unlike `id`, which changes when either of those happens.",
    "system_data": "Output only. Metadata about this resource's own creation and last modification -- who made the change and when.",
    "sku": "The pricing tier and capacity this resource is provisioned at.",
    "tier": "The service tier this resource (or its `sku`) is provisioned at, e.g. `Standard` or `Premium`.",
    "kind": "A finer-grained classification of this resource within its own resource type, when the type supports more than one variant.",
    "zones": "The Availability Zone(s) this resource is pinned to, within its own region.",
    "extended_location": "The edge or custom location (e.g. an Azure Extended Zone or Arc-connected site) this resource is deployed to, when it isn't a standard Azure region.",
    "principal_id": "Output only. The Microsoft Entra ID object ID of this resource's own managed identity or service principal.",
    "tenant_id": "Output only. The Microsoft Entra ID tenant this resource's own managed identity belongs to.",
    "identity": "The managed identity (or identities) this resource uses to authenticate to other Azure services.",
}

# Real, live-verified (Microsoft.Network's own well-documented, stable REST
# API surface -- LoadBalancer/ApplicationGateway/VirtualNetworkGateway/
# ExpressRoute/VirtualWan) field names, reused verbatim across every
# azure_network_* family because ARM's Network resource provider models
# nearly everything (subnets, IP configs, security rules, gateways) as
# cross-references into the SAME shared object graph -- this is the same
# real pathology already identified and describe_exclude'd for
# azure_network_virtualnetwork itself; these dictionaries cover the
# genuinely-included remainder of that same graph in the other network
# families.
ARM_NETWORK = {
    "subnet": "A reference to the subnet this resource is associated with.",
    "subnets": "The subnets belonging to this virtual network or gateway.",
    "private_ipaddress": "The private (internal) IP address assigned to this IP configuration.",
    "private_ipallocation_method": "Whether `private_ipaddress` is `Static` (fixed, caller-assigned) or `Dynamic` (assigned automatically from the subnet's own range).",
    "public_ipaddress": "A reference to the Public IP Address resource associated with this IP configuration.",
    "ip_configurations": "The IP configuration(s) (private/public address, subnet) attached to this resource.",
    "nat_gateway": "A reference to the NAT Gateway this subnet or IP configuration routes outbound traffic through.",
    "service_gateway": "A reference to the service (VPN/ExpressRoute) gateway associated with this resource.",
    "priority": "The relative priority of this rule -- lower numbers are evaluated first, and the first matching rule wins.",
    "access": "Whether this security rule's own match is `Allow`ed or `Deny`ed.",
    "direction": "Whether this security rule applies to `Inbound` or `Outbound` traffic.",
    "destination_address_prefix": "The destination IP address range (CIDR) or tag this rule matches, e.g. `10.0.0.0/24` or `Internet`.",
    "destination_address_prefixes": "The destination IP address ranges (CIDR) this rule matches, when more than one applies.",
    "destination_application_security_groups": "The Application Security Groups this rule matches traffic destined for, instead of a raw address prefix.",
    "destination_port_range": "The destination port range this rule matches, e.g. `80` or `1000-2000`.",
    "destination_port_ranges": "The destination port ranges this rule matches, when more than one applies.",
    "source_address_prefix": "The source IP address range (CIDR) or tag this rule matches, e.g. `10.0.0.0/24` or `Internet`.",
    "source_address_prefixes": "The source IP address ranges (CIDR) this rule matches, when more than one applies.",
    "source_application_security_groups": "The Application Security Groups this rule matches traffic originating from, instead of a raw address prefix.",
    "source_port_range": "The source port range this rule matches, e.g. `*` for any port.",
    "source_port_ranges": "The source port ranges this rule matches, when more than one applies.",
    "protocol": "The network protocol this rule or listener applies to, e.g. `Tcp`, `Udp`, or `*` for any.",
    "idle_timeout_in_minutes": "How many minutes an idle connection is kept open before this resource closes it.",
    "ddos_settings": "DDoS protection configuration for this public IP or virtual network.",
    "ddos_custom_policy": "A reference to a custom DDoS protection policy to apply, overriding the subscription's own default DDoS policy.",
    "fqdn": "The fully qualified domain name assigned to this resource.",
    "enabled": "Whether this feature or setting is turned on.",
    "description": "A user-supplied, human-readable note explaining this resource's own purpose.",
    "public_ipprefix": "A reference to the Public IP Prefix resource this address is allocated from.",
    "network_interfaces": "The network interface(s) attached to this resource.",
    "ip_address": "An IP address value.",
    "link": "A reference to a related resource.",
    "linked_resource_type": "The Azure resource type of the resource `link` points to.",
    "locations": "The Azure region(s) this configuration or availability applies to.",
    "service": "The Azure service (e.g. a specific Private Link-enabled PaaS service) this configuration applies to.",
    "address_prefix": "An IP address range in CIDR notation, e.g. `10.0.0.0/24`.",
    "dns_settings": "DNS configuration for this public IP address, controlling its own domain name label and reverse DNS record.",
    "migration_phase": "Which phase of a live migration (e.g. between IP address versions or gateway SKUs) this resource is currently in.",
    "private_link_service_connection_state": "The current approval state of this private endpoint's own connection to the target Private Link service -- whether it's been approved, rejected, or still pending, and any action the service owner still needs to take.",
    "actions_required": "Output only. Any action the Private Link service owner still needs to take on this connection beyond the basic approve/reject/disconnect workflow, or `None` if nothing further is needed.",
    "status": "The current status of this connection, resource, or operation, e.g. `Approved`, `Pending`, `Rejected`, or `Disconnected`.",
    "private_ipaddress_version": "Whether the private IP address for this configuration is `IPv4` or `IPv6`.",
    "ddos_protection_plan": "A reference to the DDoS Protection Plan covering this virtual network.",
    "protection_mode": "Whether DDoS protection for this resource is `Enabled`, `Disabled`, or inherits from the containing virtual network.",
    "delete_option": "What happens to this resource when its own parent (e.g. the VM or NIC it's attached to) is deleted -- `Delete` it too, or `Detach` and leave it standing.",
    "domain_name_label": "The DNS label whose concatenation with the region's own DNS zone forms this public IP address's fully qualified domain name.",
    "domain_name_label_scope": "How uniquely `domain_name_label` must be scoped -- e.g. tenant-wide or subscription-wide -- when generating this address's own FQDN.",
    "reverse_fqdn": "A fully qualified domain name that resolves to this public IP address, creating a matching reverse-DNS (PTR) record.",
    "ip_configuration": "A reference to the IP configuration this resource is associated with.",
    "ip_tags": "IP address tags -- provider-assigned category labels (e.g. for a specific Azure service edge) attached to this public IP address.",
    "first_party_service_tag_id": "The identifier of the Microsoft first-party service tag this IP tag is associated with.",
    "ip_tag_type": "The category this IP tag belongs to, e.g. `FirstPartyUsage`.",
    "tag": "The literal tag value.",
    "linked_public_ipaddress": "A reference to a second Public IP Address resource this one is linked to, e.g. its own IPv4/IPv6 counterpart.",
    "nat64": "Whether NAT64 (IPv6-to-IPv4 translation) is enabled for this configuration.",
    "public_ip_addresses": "The IPv4 Public IP Address resources associated with this configuration.",
    "public_ip_addresses_v6": "The IPv6 Public IP Address resources associated with this configuration.",
    "public_ip_prefixes": "The IPv4 Public IP Prefix resources associated with this configuration.",
    "public_ip_prefixes_v6": "The IPv6 Public IP Prefix resources associated with this configuration.",
    "source_virtual_network": "A reference to the virtual network this resource is sourced from.",
    "public_ipaddress_version": "Whether this public IP address is `IPv4` or `IPv6`.",
    "public_ipallocation_method": "Whether this public IP address is `Static` (fixed for the resource's lifetime) or `Dynamic` (may change if the resource is deleted and recreated).",
    "service_public_ipaddress": "The Public IP Address resource this managed service uses for outbound/inbound connectivity.",
    "upgraded_to_v2": "Whether this resource has been upgraded to its own newer, v2 SKU/architecture.",
    "network_security_group": "A reference to the Network Security Group applied to this subnet or network interface.",
    "primary": "Whether this is the primary configuration among several attached to the same resource.",
    "client_id": "The client (application) ID of the user-assigned managed identity to use.",
    "user_assigned_identities": "The user-assigned managed identities associated with this resource, keyed by their own resource ID.",
    "enabled_filtering_criteria": "Which traffic characteristics this flow log filters on before recording.",
    "flow_analytics_configuration": "Configuration for deriving Traffic Analytics insights from this flow log's own recorded data.",
    "network_watcher_flow_analytics_configuration": "Traffic Analytics settings (workspace, interval) applied to this Network Watcher flow log.",
    "traffic_analytics_interval": "How often, in minutes, Traffic Analytics processes this flow log's own data into insights.",
    "workspace_id": "The Log Analytics workspace ID Traffic Analytics results are sent to.",
    "workspace_region": "The Azure region the target Log Analytics workspace is deployed in.",
    "workspace_resource_id": "The full Azure Resource Manager resource ID of the target Log Analytics workspace.",
    "format": "The output format this data is written in.",
    "version": "The format or schema version this data conforms to.",
    "record_types": "Which categories of record this configuration includes.",
    "retention_policy": "How long this flow log's own recorded data is kept before automatic deletion.",
    "days": "The number of days data is retained before automatic deletion.",
    "storage_id": "The resource ID of the storage account this flow log's own data is written to.",
    "target_resource_guid": "Output only. The stable `resource_guid` of the resource this flow log is enabled on.",
    "target_resource_id": "The resource ID this configuration applies to, e.g. the NSG or virtual network a flow log is enabled on.",
    "default_security_rules": "Output only. The built-in security rules Azure automatically adds to every Network Security Group, which can't be removed (only overridden by a higher-priority custom rule).",
    "flow_logs": "The flow log(s) configured on this Network Security Group.",
    "flush_connection": "Whether existing, already-established connections are re-evaluated (and dropped if no longer allowed) immediately when this security rule changes, rather than only affecting new connections.",
    "group_ids": "The sub-resource(s) of the target service this private endpoint connects to, e.g. `blob` for a Storage account's blob endpoint.",
    "private_link_service_id": "The resource ID of the Private Link service (or Private Link-enabled PaaS resource) this private endpoint connects to.",
    "security_rules": "The custom (non-default) security rules on this Network Security Group.",
    "gateway_load_balancer": "A reference to a Gateway Load Balancer this resource chains its traffic through, for third-party network virtual appliance inspection.",
    "inbound_nat_rules": "The inbound NAT rules on this load balancer, each forwarding one external port to one specific backend instance.",
    "load_balancing_rules": "The load-balancing rules on this load balancer, each mapping a frontend IP/port to a backend pool.",
    "outbound_rules": "The outbound NAT rules on this load balancer, controlling how backend instances reach the internet through it.",
    "actions": "The action(s) this rule or policy applies.",
    "service_name": "The name of the Azure service this configuration applies to or connects with.",
    "allocated_address_prefixes": "Output only. The specific address ranges actually allocated from this pool.",
    "number_of_ip_addresses": "How many IP addresses to allocate from this pool.",
    "pool": "A reference to the address or backend pool this resource draws from or belongs to.",
    "has_bgp_override": "Whether a static route on this route table overrides the equivalent route learned via BGP.",
    "next_hop": "Where traffic matching this route is sent next.",
    "next_hop_ip_address": "The IP address traffic matching this route is forwarded to, when `next_hop_type` is `VirtualAppliance`.",
    "next_hop_ip_addresses": "Output only. The effective next-hop IP address(es) actually in use for this route.",
    "next_hop_type": "The kind of next hop this route uses, e.g. `VirtualAppliance`, `VnetLocal`, `Internet`, or `None`.",
    "allow_delete": "Whether this resource can be deleted directly, or is protected because something else still depends on it.",
    "contextual_service_endpoint_policies": "Service endpoint policies that apply to this subnet only in specific contexts (e.g. a specific service alias), layered on top of its own regular `service_endpoint_policies`.",
    "service_alias": "The alias identifying the specific PaaS service resource a service endpoint policy definition grants access to.",
    "service_endpoint_policy_definitions": "The individual rules making up a service endpoint policy, each granting subnet traffic access to a specific Azure service resource.",
    "service_resources": "The specific service resource(s) a service endpoint policy definition grants access to.",
    "network_identifier": "An identifier for the network this configuration is scoped to.",
    "address_prefixes": "The IP address ranges (CIDR), in the plural form, this resource covers.",
    "application_gateway_ipconfigurations": "The IP configuration(s) an Application Gateway uses within this subnet.",
    "default_outbound_access": "Whether this subnet gets default outbound internet access without an explicit NAT Gateway, load balancer, or public IP.",
    "delegations": "Delegates this subnet's own control to a specific Azure PaaS service, letting that service manage resources directly inside it.",
    "ip_allocations": "References to IP address pool allocations reserved for this subnet.",
    "ip_configuration_profiles": "Reusable IP configuration templates associated with this resource.",
    "ipam_pool_prefix_allocations": "Address prefixes allocated to this virtual network from an IP Address Management (IPAM) pool.",
    "private_endpoint": "A reference to the Private Endpoint resource this connection belongs to.",
    "private_endpoint_network_policies": "Whether network security group and route table policies are enforced (`Enabled`) or bypassed (`Disabled`) for private endpoints in this subnet.",
    "private_endpoints": "The Private Endpoint resources deployed in this subnet.",
    "private_link_service_network_policies": "Whether network security group and route table policies are enforced (`Enabled`) or bypassed (`Disabled`) for Private Link services in this subnet.",
    "purpose": "Output only. What this resource is being used for, when it was created automatically on behalf of another resource.",
    "resource_navigation_links": "Output only. Links to the specific external resource(s) that own or manage this subnet, when it was delegated to or created by another Azure service.",
    "route_table": "A reference to the route table associated with this subnet.",
    "disable_bgp_route_propagation": "Whether routes learned via BGP are prevented from propagating into this route table.",
    "disable_peering_route": "Whether this route is withheld from propagating to a peered virtual network.",
    "routes": "The custom routes making up this route table.",
    "service_association_links": "Output only. Links identifying the Azure service(s) this subnet has been associated with, e.g. by delegation.",
    "request_message": "A message the requester attaches when asking to connect to this Private Link-enabled or ExpressRoute-peered resource, shown to the approver alongside the connection request.",
    "group_id": "The sub-resource this connection targets on the destination service, e.g. `blob` for a Storage account's blob endpoint.",
    "application_security_groups": "The Application Security Group(s) this network interface's IP configuration belongs to, letting security rules elsewhere match traffic to/from it by group membership instead of by raw IP.",
    "subscriptions": "The subscription ID(s) this auto-approval or visibility rule applies to.",
    "fqdns": "The fully qualified domain name(s) associated with this resource.",
    "frontend_port": "The external port this load-balancing or NAT rule listens on.",
    "enable_connection_tracking": "Whether this rule tracks individual connections for graceful behavior on backend pool membership changes, rather than treating every packet independently.",
    "backend_port": "The port on the backend instance this rule forwards matched traffic to.",
    "inbound_nat_pools": "A range of ports reserved on the load balancer's own frontend, auto-allocated one-to-one to backend instances for inbound NAT (typically used by a scale set).",
    "backend_ipconfigurations": "The backend IP configuration(s) (e.g. NIC IP configs) that make up this backend pool.",
    "virtual_network": "A reference to the virtual network this resource is associated with.",
    "ip_addresses": "The IP address(es) associated with this resource.",
    "member_name": "The name identifying this member within its own containing group or set.",
    "billing_sku": "The billing tier for this ExpressRoute circuit, e.g. `MeteredData` (pay per GB) or `UnlimitedData` (flat rate).",
    "custom_dns_configs": "DNS records this private endpoint registers for the target service's own FQDN(s), resolved to the endpoint's private IP address.",
    "custom_network_interface_name": "A caller-chosen name for the network interface this private endpoint automatically creates, instead of an auto-generated one.",
    "ip_version_type": "Whether this configuration applies to `IPv4`, `IPv6`, or both.",
    "manual_private_link_service_connections": "Private Link service connection(s) requiring manual approval by the service owner, rather than automatic approval.",
    "private_link_service_connections": "The Private Link service connection(s) this private endpoint establishes.",
    "virtual_network_tap": "A reference to the Virtual Network TAP this configuration mirrors traffic to.",
    "link_identifier": "Output only. A unique identifier for this specific ExpressRoute physical link within its own port.",
    "private_endpoint_connections": "Output only. The Private Endpoint connections currently established to this resource.",
    "auxiliary_mode": "The auxiliary networking mode for this network interface -- e.g. `MaxConnections` or `Floating`, used for network appliance scenarios needing more than the standard connection limits.",
    "auxiliary_sku": "The SKU sizing the auxiliary networking capacity `auxiliary_mode` provides for this network interface.",
    "default_outbound_connectivity_enabled": "Whether this network interface gets default outbound internet access without an explicit NAT Gateway, load balancer, or public IP.",
    "disable_tcp_state_tracking": "Whether this network interface skips TCP connection state tracking, typically for network virtual appliances that need to see raw, untracked packet flow.",
    "applied_dns_servers": "Output only. The effective DNS server IP addresses this network interface actually uses, resolved from `dns_servers` or the virtual network's own defaults.",
    "dns_servers": "Custom DNS server IP addresses this resource uses, overriding the virtual network's own default DNS.",
    "internal_dns_name_label": "A DNS label for this network interface, resolvable from within the virtual network as `{label}.{internal_domain_name_suffix}`.",
    "internal_domain_name_suffix": "Output only. The DNS suffix appended to `internal_dns_name_label` to form this network interface's own internal FQDN.",
    "internal_fqdn": "Output only. This network interface's own resolvable internal fully qualified domain name.",
    "dscp_configuration": "A reference to the DSCP (traffic prioritization) configuration applied to this network interface.",
    "enable_accelerated_networking": "Whether accelerated networking (SR-IOV-based, lower-latency networking) is enabled on this network interface.",
    "enable_ipforwarding": "Whether this network interface can forward traffic not addressed to one of its own IP addresses -- required for network virtual appliance scenarios.",
    "hosted_workloads": "Output only. The resource ID(s) of workloads (e.g. Private Link services) currently hosted on this network interface.",
    "mac_address": "Output only. The MAC address assigned to this network interface.",
    "nic_type": "Whether this is a `Standard` network interface or `Elastic` (used by certain high-performance appliance scenarios).",
    "private_link_service": "A reference to the Private Link service this resource connects to or exposes.",
    "access_mode": "Whether access through this resource is `Auto` (Azure-managed) or `Manual`.",
    "alias": "Output only. An auto-generated, globally unique moniker for this Private Link service, given to consumers instead of its full resource ID.",
    "auto_approval": "The subscription(s) whose private endpoint connection requests to this Private Link service are approved automatically, without the owner reviewing each one.",
    "destination_ipaddress": "The IP address this NAT rule forwards matched traffic to.",
    "enable_proxy_protocol": "Whether this resource prepends PROXY protocol headers (carrying the original client IP) to forwarded connections, so the backend can see the real source despite NAT.",
    "load_balancer_frontend_ip_configurations": "The load balancer frontend IP configuration(s) this Private Link service is exposed through.",
    "private_endpoint_location": "The region a private endpoint connecting to this Private Link service is created in, when different from the service's own region.",
    "visibility": "The subscription(s) allowed to see and request a connection to this Private Link service at all -- narrower than, and a prerequisite for, `auto_approval`.",
    "tap_configurations": "The Virtual Network TAP configuration(s) mirroring this network interface's own traffic.",
    "destination_load_balancer_front_end_ipconfiguration": "The load balancer frontend IP configuration this Virtual Network TAP mirrors traffic to.",
    "destination_network_interface_ipconfiguration": "The network interface IP configuration this Virtual Network TAP mirrors traffic to.",
    "destination_port": "The port this NAT rule forwards matched traffic to.",
    "network_interface_tap_configurations": "The Virtual Network TAP configuration(s) attached to this network interface.",
    "virtual_machine": "A reference to the virtual machine this network interface is attached to.",
    "vnet_encryption_supported": "Output only. Whether the virtual network this network interface is attached to supports VNet encryption.",
    "workload_type": "The kind of workload hosted on this network interface, when it's dedicated to a specific managed service.",
    "backend_address_pool": "A reference to the backend address pool this rule sends matched traffic to.",
    "frontend_ipconfiguration": "A reference to the frontend IP configuration this rule listens on.",
    "admin_state": "An administrative override for this rule's own health-probe-driven forwarding state -- `Up` forces new connections through regardless of probe results, `Down` forces them away.",
    "enable_tcp_reset": "Whether the load balancer sends a TCP reset when a connection is idle-timed-out or the backend becomes unavailable, so the client fails fast instead of hanging.",
    "enable_floating_ip": "Whether this rule uses Floating IP (Direct Server Return) -- the backend sees the frontend's own IP as the destination, rather than its own.",
    "backend_addresses": "The backend address(es) (by IP or NIC IP configuration) this pool routes traffic to.",
    "inbound_nat_rules_port_mapping": "Output only. The specific frontend-to-backend port mapping(s) this backend instance received from an inbound NAT pool.",
    "inbound_nat_rule_name": "The name of the inbound NAT rule this port mapping belongs to.",
    "load_balancer_frontend_ipconfiguration": "A reference to the load balancer's own frontend IP configuration this applies to.",
    "network_interface_ipconfiguration": "A reference to the network interface IP configuration this applies to.",
    "identifier": "A unique identifier for this resource or configuration.",
    "frontend_port_range_end": "The last port, inclusive, in this inbound NAT pool's own frontend port range.",
    "frontend_port_range_start": "The first port, inclusive, in this inbound NAT pool's own frontend port range.",
    "service_endpoint_policies": "Service endpoint policies restricting which specific service resources this subnet's own service endpoint traffic can reach.",
    "service_endpoints": "The Azure service(s) (e.g. `Microsoft.Storage`) this subnet has a direct, private route to via service endpoints, bypassing the public internet.",
    "sharing_scope": "How broadly this resource can be shared -- e.g. `Tenant` (any resource in the tenant) or `DelegatedServices` (only specific delegated Azure services).",
    "drain_period_in_seconds": "How long a backend instance stays reachable for existing connections after being marked for removal, before the load balancer stops routing to it entirely.",
    "load_balancer_backend_addresses": "The backend address(es) registered directly on the load balancer resource itself, rather than sourced from a NIC's own IP configuration.",
    "outbound_rule": "A reference to the outbound NAT rule associated with this resource.",
    "sync_mode": "Whether this backend pool's own membership is synced `Automatic`ally from attached NICs, or managed `Manual`ly via `load_balancer_backend_addresses`.",
    "tunnel_interfaces": "The tunnel endpoint(s) (their own IP addresses and roles) making up this VPN connection, one per active/standby tunnel instance.",
    "backend_ipconfiguration": "A reference to the backend network interface IP configuration this applies to.",
    "application_gateway_backend_address_pools": "The Application Gateway backend address pool(s) this network interface's IP configuration belongs to.",
    "load_balancer_backend_address_pools": "The Load Balancer backend address pool(s) this network interface's IP configuration belongs to.",
    "load_balancer_inbound_nat_rules": "The Load Balancer inbound NAT rule(s) this network interface's IP configuration is a target of.",
    "port": "A TCP or UDP port number.",
    "private_ipaddress_prefix_length": "The subnet mask length (CIDR prefix) applied to `private_ipaddress`.",
    "private_link_connection_properties": "The connection-specific properties (group ID, FQDNs, request message) carried by this Private Link connection.",
    "required_member_name": "The name a resource must be created with to participate in a specific availability/failover grouping.",
    "virtual_network_taps": "The Virtual Network TAP(s) mirroring this resource's own traffic.",
    "address_space": "The virtual network's own address range(s), in CIDR notation.",
    "port_range": "A range of ports, e.g. `1000-2000`.",
    "circuit_connection_status": "The connectivity state of this ExpressRoute circuit connection, e.g. `Connected` or `Connecting`.",
    "prefix": "An IP address prefix, in CIDR notation.",
    "signature": "A cryptographic signature validating this resource's own configuration or authorization.",
    "validation_id": "An identifier for a pending validation request on this resource, e.g. an ExpressRoute prefix ownership check.",
    "validation_state": "The current outcome of validating this resource's own configuration, e.g. whether an advertised prefix passed ownership verification.",
    "state": "The current operational state of this resource.",
    "public_cert_data": "The base64-encoded public certificate data used to authenticate a point-to-site VPN client.",
    "dh_group": "The Diffie-Hellman group used for IKE Phase 1 key exchange, e.g. `DHGroup14` or `DHGroup24`.",
    "ike_encryption": "The encryption algorithm used for IKE Phase 1 (establishing the secure channel itself), e.g. `AES256`.",
    "ike_integrity": "The integrity (hashing) algorithm used for IKE Phase 1, e.g. `SHA384`.",
    "ipsec_encryption": "The encryption algorithm used for IKE Phase 2 (the actual IPsec data tunnel), e.g. `AES256`.",
    "ipsec_integrity": "The integrity (hashing) algorithm used for IKE Phase 2, e.g. `SHA256`.",
    "pfs_group": "The Perfect Forward Secrecy group used when establishing a new IKE Phase 2 security association, or `None` to disable PFS.",
    "sa_data_size_kilobytes": "The IPsec security association's own data-volume lifetime, in kilobytes -- the tunnel rekeys once either this or `sa_life_time_seconds` is reached.",
    "sa_life_time_seconds": "The IPsec security association's own time-based lifetime, in seconds -- the tunnel rekeys once either this or `sa_data_size_kilobytes` is reached.",
    "express_route_circuit_peering": "A reference to the ExpressRoute circuit peering this connection uses.",
    "data": "The literal data payload of this field.",
    "peer_express_route_circuit_peering": "A reference to the peer ExpressRoute circuit's own matching peering, for a circuit connecting two ExpressRoute circuits directly.",
    "microsoft_peering_config": "Configuration for this ExpressRoute circuit's own Microsoft Peering -- routes to Microsoft SaaS services (e.g. Microsoft 365) advertised over the circuit.",
    "advertised_communities": "The BGP community value(s) attached to routes this peering advertises.",
    "advertised_public_prefix_info": "Output only. Per-prefix validation detail for each of this peering's own `advertised_public_prefixes`.",
    "advertised_public_prefixes": "The public IP address prefix(es) this Microsoft Peering advertises, e.g. `123.1.0.0/24` -- ownership of each is verified before routes go live.",
    "advertised_public_prefixes_state": "Output only. Whether `advertised_public_prefixes` has passed ownership validation, e.g. `Configured` or `ValidationNeeded`.",
    "customer_asn": "The customer's own public BGP Autonomous System Number, required for Microsoft Peering.",
    "legacy_mode": "Whether this ExpressRoute circuit uses the older, pre-IPv6-split routing configuration for Microsoft Peering.",
    "routing_registry_name": "The Internet routing registry (e.g. `ARIN`, `RIPE`) `advertised_public_prefixes` ownership is validated against.",
    "primary_peer_address_prefix": "The `/30` subnet used for the primary (redundant) link's own point-to-point connection between the customer and Microsoft edge routers.",
    "secondary_peer_address_prefix": "The `/30` subnet used for the secondary (redundant) link's own point-to-point connection between the customer and Microsoft edge routers.",
    "custom_bgp_ip_addresses": "Caller-chosen BGP peering IP addresses to use for this connection, instead of Azure's own auto-allocated defaults.",
    "default_bgp_ip_addresses": "Output only. The BGP peering IP address(es) Azure auto-allocated for this connection.",
    "ipconfiguration_id": "A reference to the IP configuration this applies to.",
    "ip_configuration_id": "A reference to the IP configuration this applies to.",
    "tunnel_ip_addresses": "Output only. The public IP address(es) of this VPN gateway's own tunnel endpoint(s).",
}
